data_preparation:
  analyse_tree: False
  input_data: "d_data/data/thnsparse/AnalysisResults_24_minbias.root"
  input_mc: "d_data/mc/thnsparse/AnalysisResults_25a3.root"
  output_file:  "results/prepare_data_deut_thn.root"
  bin_width: 0.25
  min_pt: 0.5
  max_pt: 3.0
  ## only used if analyse_tree is True
  n_bins_dca: 200
  max_abs_dca: 0.04

dca_analysis:
  output_file: "results/dca_analysis_deut_thn.root"
